# Configuration File

# You must set a secretkey
application:
  secret_key: putrandomgookhere

# To change the default database you must copy this file to database.yml and
# change the hostspec to connect to your database.
#   hostspec: <protocol>://<user>:<password>@<host>/<database name>
databases:
  production:
    hostspec: favsql://exuser:expass@example.exampleaws.com/somedbname
  development:
    hostspec: mysql://bitbook:amazon@localhost/bitbook
